spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/course
    username: postgres
    password: Admin123@
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enable: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: lesson:com.htt.elearning.lesson.pojo.Lesson


server:
  port: 8050

application:
  config:
    cloudinary-url: http://localhost:8096/api/cloudinary
    user-url: http://localhost:8096/api/users
    enrollment-url: http://localhost:8096/api/enrollments
    progress-url: http://localhost:8096/api/progress
    notification-url: http://localhost:8096/api/get-notification
    firebase-url: http://localhost:8096/api/notifications
