spring:
  datasource:
    url: jdbc:mysql://localhost:3306/elearningdb
    username: root
    password: Admin123@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8092

application:
  config:
    enrollment-url: http://localhost:8080/api/enrollments
    user-url: http://localhost:8080/api/users
    token-url: http://localhost:8080/api/token