spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: enrollment-service

python:
  api:
    url: http://127.0.0.1:5000

perspective:
  api:
    key:  #key

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      user-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimum-number-of-calls: 5

  retry:
    instances:
      user-service:
        max-attempts: 3
        wait-duration: 5s

  timelimiter:
    instances:
      user-service:
        timeout-duration: 3s
