spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: notification-service

  mail:
    host: smtp.gmail.com
    port: 587
    username:  #username
    password:  #password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true