spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway-service

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimum-number-of-calls: 5

  timelimiter:
    configs:
      default:
        timeout-duration: 3s

  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 2s


logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: DEBUG

secure:
  open-paths-get:
    - /api/teachers/all
    - /api/courses/**
    - /api/teachers/users/
    - /api/teachers/get-teacher-by-userId/**
    - /api/teacher/**
    - /api/lessons/get-first-lesson/course/**
    - /api/lessons/count-by-course/**
    - /api/videos/count/**
    - /api/assignments/lesson/**
    - /api/category/**
    - /api/tags/**
    - /api/questions/count/assignment/**
    - /api/token/**
    - /api/login/auth/social-login
    - /api/login/auth/social/callback
  open-paths-post:
    - /api/users/login
    - /api/users/register
    - /api/users/register-account
    - /api/cloudinary/upload
    - /api/cloudinary/upload-image
    - /api/token
    - /api/user-overview/**
    - /api/user-interesting/**
