spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway-service

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.web: DEBUG

secure:
  open-paths-get:
    - /api/teachers/all
    - /api/courses/**
    - /api/teachers/users/
    - /api/teachers/get-teacher-by-userId/**
    - /api/lessons/get-first-lesson/course/**
    - /api/lessons/count-by-course/**
    - /api/videos/count/**
    - /api/assignments/lesson/**
    - /api/category/**
    - /api/tags/**
    - /api/questions/count/assignment/**
    - /api/token/**
  open-paths-post:
    - /api/users/login
    - /api/users/register
    - /api/users/register-account
    - /api/login/auth/social-login
    - /api/login/auth/social/callback
    - /api/cloudinary/upload
    - /api/cloudinary/upload-image
    - /api/token
