spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: cloudinary-service
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

cloudinary:
  cloud-name:  #my_cloud_name
  api-key:  #my_api_key
  api-secret:   #my_api_secret