spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: COURSES-SERVICE
  data:
    redis:
      port: 6379
      host: localhost
      use-redis-cache: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

python:
  api:
    url: http://127.0.0.1:5000

jwt:
  expiration: 2592000
  secretKey:  #secretKey

#feign:
#  circuitbreaker:
#    enabled: true

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      user-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimum-number-of-calls: 5

  retry:
    instances:
      user-service:
        max-attempts: 3
        wait-duration: 5s

  timelimiter:
    instances:
      user-service:
        timeout-duration: 3s


