spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: COURSES-SERVICE
  data:
    redis:
      port: 6379
      host: localhost
      use-redis-cache: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

python:
  api:
    url: http://127.0.0.1:5000

jwt:
  expiration: 2592000
  secretKey:  #secretKey #secretKey

